### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by norewp** [ControlledChaos/controlled-chaos-theme#1]
Getting the following Error on frontend after theme activation
`Fatal  error: Cannot declare class Controlled_Chaos\Controlled_Chaos_Content,  because the name is already in use in  C:\wamp64\www\wordpress\wp-content\themes\controlled-chaos\template-parts\content\content.php  on line 18
--`

P.S. functions.php has `ControlledChaos` as the namespace  - should that not be `Controlled_Chaos`

**Comment by ControlledChaos** [comment]
Fixed the namespace. Was correct locally. Not sure what happen to the underscore.

**Comment by ControlledChaos** [comment]
Fixed content class looping through blog pages.

**Comment by norewp** [comment]
Confirmed as fixed, thanks :)
